# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Diff Read
email: darrynsoper@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Break down your Github .diff file into readable, step-by-step instructions of code alterations.
baseurl: "https://darryn.github.io/diff-read" # the subpath of your site, e.g. /blog
url: "https://darryn.github.io/diff-read" # the base hostname & protocol for your site
github_username:  darryn

# Build settings
markdown: kramdown
